/* GENERATED by build.mjs from demo-data.js — do not edit by hand. */
window.DEMO = {
 "practice": {
  "name": "Elite Medical Skin and Laser Center",
  "shortName": "Elite",
  "domain": "myeliteskin.com",
  "logoDark": "assets/logo-dark.webp",
  "logoLight": "assets/logo-light.webp",
  "phone": "281-214-7777",
  "phoneHref": "+12812147777",
  "instagram": "https://www.instagram.com/myeliteskin",
  "instagramHandle": "@myeliteskin",
  "tagline": "Love the skin you’re in.",
  "story": "Founded in Spring in 2007 by Tonya Cariker, working with Dr. Christine Cheng. One clinic on Richards Road, serving Spring and The Woodlands."
 },
 "sandy": {
  "name": "Sandy",
  "role": "AI receptionist",
  "voice": "Aoede",
  "model": "gemini-3.1-flash-live-preview",
  "tuning": {
   "endSensitivity": "END_SENSITIVITY_LOW",
   "silenceMs": 1400,
   "thinkingLevel": "LOW",
   "proactiveAudio": false,
   "affectiveDialog": false
  },
  "talkingPoints": {
   "Botox": "The wrinkle relaxer most people have heard of. It softens the lines that come from movement — forehead, frown lines, crow’s feet — and is also used for jaw clenching and for excessive sweating. It suits somebody who wants the familiar, well-understood option.",
   "Xeomin": "Sometimes called a clean tox because it has no additional proteins in the formula. It is often discussed with people who have had a lot of injectables over the years and want a stripped-back alternative.",
   "Juvéderm filler": "A hyaluronic acid filler used for lips, smile lines, cheeks and jawline. It adds volume and contour rather than relaxing movement, which is the fundamental difference between filler and tox.",
   "Radiesse": "A filler that adds structure and also encourages your own collagen. It is chosen for cheeks, jawline and deeper smile lines where shape is the point. It is not used in lips.",
   "Revanesse lip filler": "A filler designed specifically for lips, aiming for soft volume with less swelling afterwards. Chosen by people who want a natural but noticeable change to the lip itself.",
   "SKINVIVE": "An injectable that is about hydration rather than volume. It uses a modified hyaluronic acid to smooth and hydrate the cheeks, so it suits dullness, dryness and crepey texture rather than lines you want filled.",
   "PDO thread lift": "Dissolvable threads placed under the skin to reposition tissue and encourage collagen along the thread line as they dissolve. Chosen for the jawline, cheeks and neck by people looking for something between injectables and surgery.",
   "HydraFacial": "Cleansing, exfoliation, extraction and hydration in one treatment, tailored after a look at your skin. Elite are an ALI Gold Partner for it, which is HydraFacial’s own recognition. It suits regular maintenance between clinical treatments.",
   "HydraFacial Keravive": "The scalp version. It cleanses and hydrates the scalp itself, and is usually discussed alongside hair concerns rather than facial skin.",
   "Microneedling": "Very fine needles create controlled micro-channels that prompt the skin to rebuild collagen over the following weeks. Usually a short course rather than a single visit. Elite hold an Aesthetic Laser Microneedling Provider Award for it.",
   "Chemical peel": "A controlled exfoliation that lifts away surface build-up so newer skin comes through. Strength is chosen to match your skin and how much recovery time you can take.",
   "Dermaplaning": "A blade is used to remove surface dead skin and fine vellus hair, which leaves the skin smoother and helps products absorb. Often combined with a facial.",
   "Diamond Glow facial": "Exfoliation, extraction and a serum infusion in one pass. A good option when somebody wants visible freshening without recovery time.",
   "PRP cocktail facial": "Uses a component of your own blood, prepared in clinic, applied alongside microneedling to support the skin’s repair process. Chosen for overall texture and tone.",
   "Laser hair removal": "A course of treatments that targets hair while it is in its active growth phase, which is why it is spaced across several sessions. This is the treatment Elite have been voted best in The Woodlands for four separate years, and there is a membership built around it.",
   "Laser tattoo removal": "A laser breaks up the ink so the body can gradually clear it. It takes a series of sessions spaced out over months, and the number depends on the ink, the age of the tattoo and where it is.",
   "Laser vein removal": "Treats small surface veins, most often on the legs and face. A consultation establishes whether the veins you are seeing are the kind this treats.",
   "Pixel laser resurfacing": "A fractional resurfacing laser for texture, tone and sun damage. It is the more intensive end of the laser menu and needs planning around your calendar, so aftercare gets covered properly at consultation.",
   "ClearLift": "A gentler laser option for tone and firmness, often chosen by people who cannot take time away from work and want something they can have and carry on with their day.",
   "Photorejuvenation": "Light-based treatment aimed at redness, pigment and general unevenness. Usually a short course, and often paired with a skincare plan.",
   "CoolSculpting": "A non-invasive body contouring treatment that cools targeted fat cells. Elite are an Allergan CoolSculpting Gold Partner. It is for specific pockets rather than overall size, and the consultation is about whether it fits what you are actually asking for.",
   "CoolTone": "Uses magnetic muscle stimulation to strengthen, tone and firm muscle in the abdomen, glutes and thighs — Elite’s own description. They are the number one CoolTone provider in Texas. There is also a pelvic floor application, which clients do talk about.",
   "Viora body contouring": "A body contouring treatment used on its own or alongside CoolTone and CoolSculpting as part of a plan. Which combination suits you is a consultation question.",
   "PRP hair restoration": "Uses a component of your own blood to support the scalp and hair follicles. Done as a series, and discussed alongside the rest of the hair loss options.",
   "Peptide therapy": "Peptides are short chains of amino acids that act as messengers, supporting processes your body already runs — repair, recovery, skin quality. Elite run it as a medically guided programme with an RN overseeing it, not as a one-off injection.",
   "EVEXIPEL hormone consultation": "Bioidentical hormone pellet therapy, starting with a consultation about your history and whether it is appropriate for you. It is a medical programme with monitoring, so the first appointment is a conversation.",
   "IV drip therapy": "Hydration and nutrients delivered by drip, usually as part of a wider wellness plan rather than on its own.",
   "B12 lipotropic shot": "A quick vitamin injection, normally part of a wellness or weight programme rather than a standalone treatment.",
   "Nutrition coaching": "With a certified nutrition coach on the team, so the food side of a wellness plan is handled by somebody qualified rather than left as a leaflet.",
   "VISIA complexion analysis": "A complexion analysis camera that photographs what is below the surface — sun damage, texture, pores, redness, porphyrins. It turns \"my skin looks tired\" into something specific enough to plan around.",
   "Membership": "Three tiers — Silver, Gold and Platinum. Each one includes a set number of treatments a month, a reduced rate on injectables and a discount on skincare, and the higher tiers include more of each. They run month to month and can be changed or cancelled at any time. I do not quote figures out loud — the tiers and what they cost are set out on the membership section of this page, and the front desk will walk you through them.",
   "Consultation": "Where everything starts, and it is free. A provider looks at your skin, listens to what is bothering you, explains the options, and you decide from there."
  },
  "soundsLike": [
   "\"CoolTone\" may be heard as cool town, cool tune or cold tone.",
   "\"CoolSculpting\" may be heard as cool sculpting, cool scalping or coal sculpting.",
   "\"HydraFacial\" may be heard as hydro facial or hydra facial.",
   "\"Keravive\" may be heard as kera vive, kara vive or caravive.",
   "\"Viora\" may be heard as viora, fiora, veeora or via.",
   "\"SKINVIVE\" may be heard as skin vive, skin five or skinny five.",
   "\"Revanesse\" may be heard as revenues, rev a ness or renaissance.",
   "\"Juvéderm\" may be heard as juvederm, juva derm or java derm.",
   "\"Xeomin\" may be heard as zeomin, xeo min or see o min.",
   "\"EVEXIPEL\" may be heard as evexipel, evexa pell or evexia.",
   "\"VISIA\" may be heard as visia, vizia or visa.",
   "\"ClearLift\" may be heard as clear lift or clear left.",
   "\"Elite Medical Skin and Laser Center\" may be heard as elite medical or my elite skin."
  ],
  "greetingCard": "Hi, this is Sandy at Elite Medical Skin and Laser Center. I can explain any treatment, tell you what the memberships include, and take a booking for you. What are you thinking about?",
  "panelLede": "Ask me anything about Elite’s treatments, the memberships or the opening hours, and I can book you a time. I answer out loud.",
  "eyebrow": "Your virtual assistant",
  "heading": "Meet Sandy, the front desk that never goes home.",
  "lede": "She knows every treatment Elite offer, the opening hours, the memberships and how the booking works. Ask her out loud — she answers in about a second.",
  "asks": [
   "“What is the difference between CoolTone and CoolSculpting?”",
   "“What is in the Gold membership?”",
   "“Do you do laser hair removal on the back?”",
   "“Can I come after work on a Thursday?”",
   "“Book me a consultation next week.”"
  ],
  "extraFacts": [
   "Elite have been in Spring since 2007. The clinic is at 25501 Richards Road, Suite 102, just west of I-45 North off Rayford Sawdust.",
   "Consultations are free.",
   "Open Monday nine to five, Tuesday and Thursday nine to nine, Wednesday nine to eight, Friday nine to three. Closed Saturday and Sunday.",
   "Pre and post-treatment instructions are published for every treatment, and clients are pointed to the right one before they come in.",
   "Medical-grade skincare stocked in clinic includes Skinbetter Science, EltaMD, PCA Skin, SkinMedica and Glymed+."
  ]
 },
 "locations": [
  {
   "id": "spring",
   "name": "Spring",
   "address": "25501 Richards Rd, Suite 102, Spring, TX 77386",
   "hint": "Just west of I-45 North, off Rayford Sawdust",
   "parking": "Parking on site at the Richards Road suites.",
   "lat": 30.1265679,
   "lon": -95.4333877,
   "hours": {
    "1": [
     9,
     17
    ],
    "2": [
     9,
     21
    ],
    "3": [
     9,
     20
    ],
    "4": [
     9,
     21
    ],
    "5": [
     9,
     15
    ]
   }
  }
 ],
 "bookable": [
  {
   "id": "consult",
   "group": "Start here",
   "name": "Consultation",
   "mins": 30,
   "note": "Free"
  },
  {
   "id": "visia",
   "group": "Start here",
   "name": "VISIA complexion analysis",
   "mins": 30
  },
  {
   "id": "botox",
   "group": "Injectables",
   "name": "Botox",
   "mins": 30
  },
  {
   "id": "xeomin",
   "group": "Injectables",
   "name": "Xeomin",
   "mins": 30
  },
  {
   "id": "juvederm",
   "group": "Injectables",
   "name": "Juvéderm filler",
   "mins": 60
  },
  {
   "id": "radiesse",
   "group": "Injectables",
   "name": "Radiesse",
   "mins": 60
  },
  {
   "id": "lips",
   "group": "Injectables",
   "name": "Revanesse lip filler",
   "mins": 45
  },
  {
   "id": "skinvive",
   "group": "Injectables",
   "name": "SKINVIVE",
   "mins": 30
  },
  {
   "id": "pdo",
   "group": "Injectables",
   "name": "PDO thread lift",
   "mins": 90
  },
  {
   "id": "hydrafacial",
   "group": "Skin",
   "name": "HydraFacial",
   "mins": 60
  },
  {
   "id": "keravive",
   "group": "Skin",
   "name": "HydraFacial Keravive",
   "mins": 60
  },
  {
   "id": "microneedling",
   "group": "Skin",
   "name": "Microneedling",
   "mins": 60
  },
  {
   "id": "peel",
   "group": "Skin",
   "name": "Chemical peel",
   "mins": 45
  },
  {
   "id": "dermaplaning",
   "group": "Skin",
   "name": "Dermaplaning",
   "mins": 45
  },
  {
   "id": "diamondglow",
   "group": "Skin",
   "name": "Diamond Glow facial",
   "mins": 60
  },
  {
   "id": "prp-facial",
   "group": "Skin",
   "name": "PRP cocktail facial",
   "mins": 75
  },
  {
   "id": "lhr",
   "group": "Laser",
   "name": "Laser hair removal",
   "mins": 30
  },
  {
   "id": "tattoo",
   "group": "Laser",
   "name": "Laser tattoo removal",
   "mins": 30
  },
  {
   "id": "vein",
   "group": "Laser",
   "name": "Laser vein removal",
   "mins": 30
  },
  {
   "id": "pixel",
   "group": "Laser",
   "name": "Pixel laser resurfacing",
   "mins": 75
  },
  {
   "id": "clearlift",
   "group": "Laser",
   "name": "ClearLift",
   "mins": 45
  },
  {
   "id": "photofacial",
   "group": "Laser",
   "name": "Photorejuvenation",
   "mins": 45
  },
  {
   "id": "coolsculpting",
   "group": "Body",
   "name": "CoolSculpting",
   "mins": 60
  },
  {
   "id": "cooltone",
   "group": "Body",
   "name": "CoolTone",
   "mins": 30
  },
  {
   "id": "viora",
   "group": "Body",
   "name": "Viora body contouring",
   "mins": 45
  },
  {
   "id": "prp-hair",
   "group": "Body",
   "name": "PRP hair restoration",
   "mins": 60
  },
  {
   "id": "peptides",
   "group": "Wellness",
   "name": "Peptide therapy consultation",
   "mins": 30
  },
  {
   "id": "hormones",
   "group": "Wellness",
   "name": "EVEXIPEL hormone consultation",
   "mins": 30
  },
  {
   "id": "iv",
   "group": "Wellness",
   "name": "IV drip therapy",
   "mins": 45
  },
  {
   "id": "b12",
   "group": "Wellness",
   "name": "B12 lipotropic shot",
   "mins": 15
  },
  {
   "id": "nutrition",
   "group": "Wellness",
   "name": "Nutrition coaching",
   "mins": 30
  }
 ],
 "treatments": [
  {
   "name": "Injectables",
   "image": "assets/svc-injectables.webp",
   "href": "https://myeliteskin.com/injectables-spring-tx/",
   "items": [
    "Botox · Xeomin · Jeuveau · Daxxify",
    "Juvéderm · Radiesse · RHA",
    "Revanesse Lips · Revanesse Versa",
    "SKINVIVE — injectable hydration",
    "PDO thread lift"
   ]
  },
  {
   "name": "Skin",
   "image": "assets/svc-skin.webp",
   "href": "https://myeliteskin.com/non-invasive-cosmetic-skin-treatments/",
   "items": [
    "HydraFacial · Keravive",
    "Microneedling · Microneedling with VAMP",
    "Chemical peel · Dermaplaning",
    "Diamond Glow · HydroJelly mask",
    "PRP cocktail facial · PRP/PRF injections",
    "VISIA complexion analysis"
   ]
  },
  {
   "name": "Laser",
   "image": "assets/svc-laser.webp",
   "href": "https://myeliteskin.com/laser-hair-removal-spring-tx/",
   "items": [
    "Laser hair removal",
    "Laser tattoo removal",
    "Laser vein removal",
    "Pixel laser resurfacing",
    "ClearLift · Bright & Lift",
    "Photorejuvenation · Laser skin tightening"
   ]
  },
  {
   "name": "Body",
   "image": "assets/svc-body.webp",
   "href": "https://myeliteskin.com/cooltone-coolsculpt/",
   "items": [
    "CoolSculpting",
    "CoolTone — including pelvic floor",
    "Viora body contouring",
    "Body HydraFacial · Body microneedling",
    "PRP hair restoration",
    "Skin tag removal"
   ]
  },
  {
   "name": "Wellness",
   "image": "assets/svc-wellness.webp",
   "href": "https://myeliteskin.com/peptide-therapy/",
   "items": [
    "Peptide therapy — GHK-Cu, BPC-157, Sermorelin",
    "90-day Glow Up programme",
    "90-day Metabolic Makeover",
    "EVEXIPEL hormone pellet therapy",
    "IV drip therapy · B12 lipotropic",
    "Nutrition coaching"
   ]
  }
 ],
 "products": {
  "eyebrow": "",
  "heading": "",
  "lede": "",
  "href": "",
  "items": []
 },
 "membership": {
  "eyebrow": "Membership",
  "anchor": "Three tiers, from $189 a month.",
  "anchorSub": "Recognised by the Reviewers Choice Awards as a top membership programme in 2026. Month to month, and changeable at any time.",
  "cta": "Explore membership",
  "href": "https://myeliteskin.com/membership/",
  "images": [
   "assets/member-2.webp",
   "assets/member-3.webp"
  ],
  "faq": [
   {
    "q": "Silver — $189 a month",
    "a": "One Tier 1 treatment a month, or a discounted Tier 2 treatment. Reduced rate on Botox and fillers, 5% off skincare and advertised specials, and a neck treatment included every visit."
   },
   {
    "q": "Gold — $289 a month",
    "a": "Two Tier 1 treatments a month, or one Tier 2. Ten per cent off skincare and advertised specials, and the same reduced injectable rate."
   },
   {
    "q": "Platinum — $389 a month",
    "a": "Four Tier 1 treatments a month, or two Tier 2. Fifteen per cent off skincare and advertised specials."
   },
   {
    "q": "Changing your mind",
    "a": "Memberships are month to month and can be adjusted at any time — Elite’s own answer, on their own FAQ page. It is the sentence that removes the reason most people hesitate, and it currently sits eleven screens down a page nobody reaches."
   }
  ]
 },
 "proof": {
  "rating": "4.8",
  "reviewCount": "389",
  "reviewSource": "Google",
  "award": "RCA Best Botox, Spring TX 2026",
  "awardNote": "Reviewers Choice Award, from verified Google reviews",
  "reviewers": [
   "Karen B.",
   "Darla O."
  ],
  "stats": [
   {
    "n": "4.8",
    "label": "Average Google rating"
   },
   {
    "n": "389",
    "label": "Google reviews"
   },
   {
    "n": "2007",
    "label": "Serving Spring since"
   },
   {
    "n": "12",
    "label": "Awards and partner recognitions"
   }
  ]
 },
 "faq": [
  {
   "q": "I have never had anything done. Where do I start?",
   "a": "With a consultation. A provider looks at your skin, listens to what is actually bothering you and explains the options and what each involves. Plenty of people book one and decide to do nothing that day — that is a normal outcome, not a wasted appointment."
  },
  {
   "q": "What is a med spa, and how is it different from a dermatologist?",
   "a": "Cosmetic skincare is about appearance and prevention. Dermatology diagnoses and treats medical skin conditions. Elite sit on the cosmetic side, with medical-grade technology and licensed providers — and will tell you when something belongs with a dermatologist instead."
  },
  {
   "q": "Who will be treating me?",
   "a": "The team includes licensed estheticians, laser technicians, an aesthetic RN who does the injecting, and a nutrition coach. Several have been here a decade or more, and you can ask for the same provider every visit."
  },
  {
   "q": "How do I know which tox or filler is right for me?",
   "a": "That is exactly what the consultation is for. Tox relaxes the muscles that create movement lines; filler adds volume or definition. Which one, where, and how much is a judgement about your face, not a package you pick in advance."
  },
  {
   "q": "Will I look frozen or overdone?",
   "a": "That is the most common worry we hear. The approach is to enhance rather than overdo — tell your injector what you want to keep, not only what you want changed."
  },
  {
   "q": "How long do results last?",
   "a": "It depends on the product and the area. Tox is usually talked about in months, filler in a year or more, and both vary by person. Your provider will give you a realistic range for your own plan rather than a number off a chart."
  },
  {
   "q": "Does it hurt?",
   "a": "Most clients describe injectables as a quick pinch. Numbing cream is used, lidocaine is used for certain fillers, and some fillers contain a numbing agent already. Laser and resurfacing feel different again — ask about the specific treatment you are considering."
  },
  {
   "q": "How much downtime should I plan for?",
   "a": "It varies by treatment. After injectables most people carry on with their day, with some redness or swelling that settles. Resurfacing needs real planning. Tell us about any event you have coming up and we will time it properly."
  },
  {
   "q": "How should I prepare?",
   "a": "Generally, avoid sun exposure, retinols and exfoliants beforehand as directed. Elite publish pre and post-treatment instructions for every treatment they offer, and your provider will point you at the right one."
  },
  {
   "q": "What is VISIA?",
   "a": "A complexion analysis camera. It photographs what is going on under the surface — sun damage, texture, pores, redness — so the plan starts from evidence about your skin rather than from a guess."
  },
  {
   "q": "Do you treat men?",
   "a": "Yes. Every treatment is available to men, and a good number of the clients here are."
  },
  {
   "q": "How does the membership work?",
   "a": "Three tiers — Silver, Gold and Platinum — month to month, each including a set number of treatments plus a reduced rate on injectables and a discount on skincare. It can be changed or cancelled at any time by speaking to the front desk. Ask me about a tier and I will tell you what is in it; the figures are set out further down this page."
  },
  {
   "q": "When are you open?",
   "a": "Monday nine to five, Tuesday and Thursday nine to nine, Wednesday nine to eight, Friday nine to three. Closed at the weekend. The late evenings are the reason a lot of people manage to come at all."
  },
  {
   "q": "Where are you?",
   "a": "25501 Richards Road, Suite 102, Spring, Texas — just west of I-45 North, off Rayford Sawdust and Richards Road. There is parking at the suites."
  }
 ],
 "results": {
  "eyebrow": "Results",
  "heading": "Before and after, from their own cases.",
  "lede": "Elite publish these on Instagram as square cards with the labels printed on top. Here they are on the website, where somebody deciding on a treatment is actually looking.",
  "categories": [
   "Injectables",
   "Body"
  ],
  "pairs": {
   "Injectables": [
    {
     "before": "assets/ba-filler-1-before.webp",
     "after": "assets/ba-filler-1-after.webp"
    },
    {
     "before": "assets/ba-filler-2-before.webp",
     "after": "assets/ba-filler-2-after.webp"
    },
    {
     "before": "assets/ba-filler-3-before.webp",
     "after": "assets/ba-filler-3-after.webp"
    },
    {
     "before": "assets/ba-filler-4-before.webp",
     "after": "assets/ba-filler-4-after.webp"
    }
   ],
   "Body": [
    {
     "before": "assets/ba-cs-abdomen-before.webp",
     "after": "assets/ba-cs-abdomen-after.webp"
    }
   ]
  },
  "emptyNote": ""
 },
 "extraFacts": [
  "Elite have been in Spring since 2007. The clinic is at 25501 Richards Road, Suite 102, just west of I-45 North off Rayford Sawdust.",
  "Consultations are free.",
  "Open Monday nine to five, Tuesday and Thursday nine to nine, Wednesday nine to eight, Friday nine to three. Closed Saturday and Sunday.",
  "Pre and post-treatment instructions are published for every treatment, and clients are pointed to the right one before they come in.",
  "Medical-grade skincare stocked in clinic includes Skinbetter Science, EltaMD, PCA Skin, SkinMedica and Glymed+."
 ]
};
