/* GENERATED by build.mjs from demo-data.js — do not edit by hand. */
window.DEMO = {
 "practice": {
  "name": "Concierge Aesthetics",
  "shortName": "Concierge",
  "domain": "conciergeaesthetics.com",
  "logoDark": "assets/logo-dark.webp",
  "logoLight": "assets/logo-light.webp",
  "phone": "(949) 767-0000",
  "phoneHref": "+19497670000",
  "instagram": "https://www.instagram.com/conciergeaesthetics",
  "instagramHandle": "@conciergeaesthetics",
  "tagline": "Artistry + Precision + Restraint.",
  "story": "Founded in Irvine in 2009 by Stacy Vencill, PA-C, MPH, who started by renting a single treatment room from Concierge Family Practice under the mentorship of Dr. Neil Neimark, and opened the practice’s own facility on Waterworks Way in 2017. One clinic, near the Irvine Spectrum, serving Orange County."
 },
 "sandy": {
  "name": "Sandy",
  "role": "AI receptionist",
  "voice": "Aoede",
  "model": "gemini-3.1-flash-live-preview",
  "tuning": {
   "endSensitivity": "END_SENSITIVITY_LOW",
   "silenceMs": 1400,
   "thinkingLevel": "LOW",
   "proactiveAudio": false,
   "affectiveDialog": false
  },
  "talkingPoints": {
   "Consultation": "Where everything starts. Thirty minutes one-to-one with a provider, who asks what is bothering you, looks at your face as a whole, takes photographs for your record and gives you exact costs before anything happens. It is a paid appointment that is credited against treatment on the day, and there is no pressure to decide in the room.",
   "Botox Cosmetic": "The wrinkle relaxer most people have heard of. It softens the lines that come from movement — forehead, frown lines, crow’s feet. Results tend to start showing in three or four days and settle over a week or two.",
   "Dysport": "Another wrinkle relaxer, from Galderma rather than Allergan. It works on the same movement lines, and which one suits you is a conversation with your injector rather than a preference you need to arrive with. Treatments earn ASPIRE points.",
   "Lip flip": "A very small amount of relaxer at the top lip so it rolls outward slightly when you smile. It is not filler and adds no volume — people choose it when they want a subtle change to how the lip sits.",
   "Sculptra": "A biostimulator rather than a filler. Instead of adding volume on the day, it prompts your own collagen over a series of treatments, so the change comes in gradually. Chosen for overall facial volume rather than for shaping one feature.",
   "Radiesse hyperdilute": "Radiesse thinned down and used across a broader area to support skin quality and stimulate collagen, rather than to build structure in one spot. Often discussed for the neck, chest and hands.",
   "Kybella": "An injectable that dissolves fat under the chin. It is done as a course, in vials, and whether it suits you depends on what is actually creating the fullness — which is what the consultation is for.",
   "Asclera vein treatment": "An injectable for small surface veins, most often on the legs. Done per vial, usually across more than one visit.",
   "Lip filler": "Hyaluronic acid filler placed in the lip itself. Concierge treat plumping and hydration separately from lip lines, and their gallery has a lot of lip work in it, including a case followed over five years.",
   "Cheek filler": "Filler used to restore volume and support in the mid-face. It is one of the areas where full-face assessment matters most, because cheeks affect how everything below them sits.",
   "Chin filler": "Filler used to balance the chin against the rest of the profile. Frequently discussed alongside jawline work rather than on its own.",
   "Jawline filler": "Filler placed along the jaw to define the line between face and neck. It is a structural treatment, so the assessment looks at chin, cheeks and neck together.",
   "Under eye filler": "Filler in the tear trough to soften hollowing under the eye. It is one of the most technique-sensitive areas on the face, which is why it is only ever done after an in-person assessment.",
   "Temple filler": "Filler at the temples, where hollowing changes the shape of the upper face. People often notice the effect without being able to name the area.",
   "Hand filler": "Filler on the back of the hand to restore lost volume there. Concierge publish before and after photographs of it.",
   "Earlobe filler": "A small amount of filler in a stretched or thinned earlobe, usually so earrings sit properly again. Quick, and more common than people expect.",
   "BioFiller": "Filler made from a component of your own blood, prepared in clinic, rather than from a manufactured product. Chosen by people who would rather not have a synthetic filler placed.",
   "Filler dissolving": "An enzyme that breaks down hyaluronic acid filler. Concierge list it as its own treatment, which is worth knowing — it means the practice will take filler out as readily as put it in.",
   "CoolPeel CO2": "A CO2 laser used in a way that resurfaces the very top of the skin while keeping heat out of the deeper tissue. It is usually done as a course of three, with maintenance afterwards.",
   "DEKA Pulse CO2": "The deeper, more intensive CO2 resurfacing on the menu. It needs real planning around your calendar, so recovery gets covered properly at the consultation.",
   "Morpheus8": "Radiofrequency delivered through microneedles, so it works on texture and firmness below the surface as well as on top. Sold as a course of three, on face, neck, chest, hands or body.",
   "Laser Genesis": "A gentler laser aimed at redness, tone and overall evenness, with no real recovery period. Often chosen as maintenance between the bigger treatments.",
   "IPL photofacial": "Intense pulsed light for pigment, sun damage and redness. Usually a short course, and often paired with a skincare plan from the aesthetician.",
   "Laser hair removal": "A course of treatments timed to the hair growth cycle, which is why it is spaced out. Generally eight to ten visits, depending on the area and on your hair.",
   "Laser vein treatment": "A laser used on small surface veins, on the face or legs. A consultation establishes whether the veins you are seeing are the kind this treats.",
   "Laser nail fungus": "A laser treatment for fungal nails. Concierge publish before and after photographs of it, which almost nobody does.",
   "ThermiVa": "A radiofrequency treatment for vaginal rejuvenation, sold as a package of three with annual maintenance. It is a private conversation and the consultation is exactly that.",
   "HydraFacial": "Cleansing, exfoliation, extraction and hydration in one treatment. Concierge run three levels of it, and the aesthetician will tell you which one your skin actually needs rather than selling you the top one.",
   "SkinPen microneedling": "Very fine needles create controlled micro-channels that prompt the skin to rebuild collagen over the following weeks. A topical anaesthetic goes on first. Changes keep developing for around six months.",
   "Chemical peel": "A controlled exfoliation that lifts surface build-up so newer skin comes through. Concierge run the Perfect Derma Peel as well as a no-downtime option for events.",
   "Concierge custom facial": "A facial built around your skin on the day rather than a fixed protocol, in a fifty or eighty minute version. The aesthetician will also look at what you are using at home.",
   "Dermaplaning facial": "A blade removes surface dead skin and fine vellus hair, leaving the skin smoother and helping products absorb. Often added to a facial.",
   "AnteAGE exosomes": "A regenerative add-on applied after microneedling or laser to support the skin’s own repair. It is an add-on to a treatment rather than something booked on its own.",
   "Sugaring": "Hair removal using a sugar paste rather than wax. Concierge offer it across most areas, including for men.",
   "Brows and lashes": "Brow and lash tinting, and brow shaping, with the aesthetician.",
   "Medical weight loss": "A medically supervised programme using tirzepatide, dosed in steps and reviewed as you go. The first appointment is a conversation about your history and whether it is appropriate for you at all — I cannot answer that part, and neither can a website.",
   "Vitamin infusion IV": "Hydration and nutrients by drip, with optional add-ons. Usually part of a wider wellness plan rather than a one-off.",
   "Wellness booster shot": "Quick injections — NAD, glutathione, lipo B12, vitamin C and magnesium are the ones on the menu. They are boosters alongside a plan, not treatments on their own.",
   "Concierge Club": "Their membership. A treatment credit that lands every month, a saving on every unit of the wrinkle relaxers, a discount on select treatments and on all skincare, and a birthday credit each year. There are fifty places and founding pricing is locked in for the life of the membership. I do not read the figures out loud — they are set out on the membership section of this page, and the front desk will walk you through them."
  },
  "soundsLike": [
   "\"Concierge Aesthetics\" may be heard as con see air j, concierge esthetics or conservative aesthetics.",
   "\"CoolPeel\" may be heard as cool peel, cool pill or coal peel.",
   "\"DEKA\" may be heard as decca, deka or the car.",
   "\"Morpheus8\" may be heard as morpheus eight, orpheus eight or morphius.",
   "\"ThermiVa\" may be heard as thermiva, thermi va, thermal va or turmeric.",
   "\"Kybella\" may be heard as kibella, key bella or cabella.",
   "\"Sculptra\" may be heard as sculptra, sculpture or scupltra.",
   "\"Radiesse\" may be heard as radiance, radius or radiese.",
   "\"Asclera\" may be heard as a sclera, asclera or ask lara.",
   "\"Dysport\" may be heard as dysport, this port or the sport.",
   "\"BioFiller\" may be heard as bio filler or by a filler.",
   "\"SkinPen\" may be heard as skin pen or skinpin.",
   "\"AnteAGE\" may be heard as ante age, anti age or auntie age.",
   "\"AlumierMD\" may be heard as alumier, aluminium or a loo me air.",
   "\"Allē\" may be heard as alley, alle or ally.",
   "\"ASPIRE\" may be heard as aspire or a spire.",
   "\"Yoelin\" may be heard as yolin, yo lin or joelin.",
   "\"Vencill\" may be heard as vensil, van sill or pencil.",
   "\"Waterworks Way\" may be heard as water works way or waterworks weigh."
  ],
  "greetingCard": "Hi, this is Sandy at Concierge Aesthetics in Irvine. I can explain any treatment, tell you who would be treating you, and take a booking. What are you thinking about?",
  "panelLede": "Ask me anything about Concierge’s treatments, the Concierge Club or the opening hours, and I can book you a time. I answer out loud.",
  "eyebrow": "Your virtual assistant",
  "heading": "Meet Sandy, the front desk that never goes home.",
  "lede": "She knows every treatment Concierge offer, who performs them, the opening hours and how the booking works. Ask her out loud — she answers in about a second.",
  "asks": [
   "“What is the difference between CoolPeel and Morpheus8?”",
   "“Who would be doing my injections?”",
   "“What do I get with the Concierge Club?”",
   "“Can I come on a Wednesday after five?”",
   "“Book me a consultation next week.”"
  ],
  "extraFacts": [
   "Concierge Aesthetics have been in Orange County since 2009 and moved into their own facility on Waterworks Way in 2017. The clinic is at 113 Waterworks Way, Suite 340, Irvine, in the Irvine Medical Arts Building near the Irvine Spectrum.",
   "The practice was founded by Stacy Vencill, PA-C, MPH, who owns it and still injects.",
   "The medical director is Dr. Steven G. Yoelin, a board-certified ophthalmologist in Newport Beach who runs clinical trials on facial injectables.",
   "Injections are performed by physician assistants overseen by the medical director.",
   "Open Monday, Tuesday, Thursday and Friday nine to five, and Wednesday nine to six. Closed Saturday and Sunday.",
   "Concierge are an Allergan Top 500 practice — the top one per cent nationwide — and have been featured on KCAL News for Botox in Orange County.",
   "Payment: Apple Pay, gift cards, Visa, Mastercard, AMEX and Discover, plus Cherry and CareCredit financing for qualified applicants.",
   "Cancellations need twenty-four hours for appointments under two hours and forty-eight hours for longer ones. Arriving more than ten minutes late may mean rescheduling.",
   "Numbing time is included in the appointment, so there is no need to arrive early for it.",
   "Medical-grade skincare stocked in clinic: AlumierMD, AnteAGE MD, Colorescience, SkinMedica, Skinbetter Science, Nutrafol, Latisse and Upneeq.",
   "Children are welcome in the building with another adult to supervise them, but not in the treatment room. Pets stay at home; service animals are always welcome."
  ]
 },
 "locations": [
  {
   "id": "irvine",
   "name": "Irvine",
   "address": "113 Waterworks Way, Suite 340, Irvine, CA 92618",
   "hint": "The newer tan medical building, off Sand Canyon",
   "parking": "Parking at the Irvine Medical Arts Building.",
   "lat": 33.6533,
   "lon": -117.7566,
   "hours": {
    "1": [
     9,
     17
    ],
    "2": [
     9,
     17
    ],
    "3": [
     9,
     18
    ],
    "4": [
     9,
     17
    ],
    "5": [
     9,
     17
    ]
   }
  }
 ],
 "bookable": [
  {
   "id": "consult",
   "group": "Start here",
   "name": "Consultation",
   "mins": 30,
   "note": "$100, credited to treatment"
  },
  {
   "id": "botox",
   "group": "Injectables",
   "name": "Botox Cosmetic",
   "mins": 30
  },
  {
   "id": "dysport",
   "group": "Injectables",
   "name": "Dysport",
   "mins": 30
  },
  {
   "id": "lipflip",
   "group": "Injectables",
   "name": "Lip flip",
   "mins": 30
  },
  {
   "id": "sculptra",
   "group": "Injectables",
   "name": "Sculptra",
   "mins": 45
  },
  {
   "id": "radiesse",
   "group": "Injectables",
   "name": "Radiesse hyperdilute",
   "mins": 45
  },
  {
   "id": "kybella",
   "group": "Injectables",
   "name": "Kybella",
   "mins": 30
  },
  {
   "id": "asclera",
   "group": "Injectables",
   "name": "Asclera vein treatment",
   "mins": 30
  },
  {
   "id": "lips",
   "group": "Dermal fillers",
   "name": "Lip filler",
   "mins": 45
  },
  {
   "id": "cheek",
   "group": "Dermal fillers",
   "name": "Cheek filler",
   "mins": 45
  },
  {
   "id": "chin",
   "group": "Dermal fillers",
   "name": "Chin filler",
   "mins": 45
  },
  {
   "id": "jawline",
   "group": "Dermal fillers",
   "name": "Jawline filler",
   "mins": 60
  },
  {
   "id": "undereye",
   "group": "Dermal fillers",
   "name": "Under eye filler",
   "mins": 45
  },
  {
   "id": "temple",
   "group": "Dermal fillers",
   "name": "Temple filler",
   "mins": 45
  },
  {
   "id": "hand",
   "group": "Dermal fillers",
   "name": "Hand filler",
   "mins": 45
  },
  {
   "id": "earlobe",
   "group": "Dermal fillers",
   "name": "Earlobe filler",
   "mins": 30
  },
  {
   "id": "biofiller",
   "group": "Dermal fillers",
   "name": "BioFiller",
   "mins": 60
  },
  {
   "id": "dissolve",
   "group": "Dermal fillers",
   "name": "Filler dissolving",
   "mins": 30
  },
  {
   "id": "coolpeel",
   "group": "Laser + energy",
   "name": "CoolPeel CO2",
   "mins": 60
  },
  {
   "id": "deka",
   "group": "Laser + energy",
   "name": "DEKA Pulse CO2",
   "mins": 90
  },
  {
   "id": "morpheus8",
   "group": "Laser + energy",
   "name": "Morpheus8",
   "mins": 75
  },
  {
   "id": "genesis",
   "group": "Laser + energy",
   "name": "Laser Genesis",
   "mins": 45
  },
  {
   "id": "ipl",
   "group": "Laser + energy",
   "name": "IPL photofacial",
   "mins": 45
  },
  {
   "id": "lhr",
   "group": "Laser + energy",
   "name": "Laser hair removal",
   "mins": 30
  },
  {
   "id": "vein",
   "group": "Laser + energy",
   "name": "Laser vein treatment",
   "mins": 30
  },
  {
   "id": "nail",
   "group": "Laser + energy",
   "name": "Laser nail fungus",
   "mins": 30
  },
  {
   "id": "thermiva",
   "group": "Laser + energy",
   "name": "ThermiVa",
   "mins": 45
  },
  {
   "id": "hydrafacial",
   "group": "Skin health",
   "name": "HydraFacial",
   "mins": 60
  },
  {
   "id": "skinpen",
   "group": "Skin health",
   "name": "SkinPen microneedling",
   "mins": 60
  },
  {
   "id": "peel",
   "group": "Skin health",
   "name": "Chemical peel",
   "mins": 45
  },
  {
   "id": "facial",
   "group": "Skin health",
   "name": "Concierge custom facial",
   "mins": 50
  },
  {
   "id": "dermaplane",
   "group": "Skin health",
   "name": "Dermaplaning facial",
   "mins": 50
  },
  {
   "id": "exosomes",
   "group": "Skin health",
   "name": "AnteAGE exosomes",
   "mins": 45
  },
  {
   "id": "sugaring",
   "group": "Skin health",
   "name": "Sugaring",
   "mins": 30
  },
  {
   "id": "brows",
   "group": "Skin health",
   "name": "Brows and lashes",
   "mins": 30
  },
  {
   "id": "weightloss",
   "group": "Wellness",
   "name": "Medical weight loss consultation",
   "mins": 30
  },
  {
   "id": "iv",
   "group": "Wellness",
   "name": "Vitamin infusion IV",
   "mins": 45
  },
  {
   "id": "booster",
   "group": "Wellness",
   "name": "Wellness booster shot",
   "mins": 15
  }
 ],
 "treatments": [
  {
   "name": "Dermal fillers",
   "image": "assets/svc-fillers.webp",
   "href": "https://www.conciergeaesthetics.com/treatments/dermal-fillers/",
   "items": [
    "Lip filler · Cheek filler · Chin filler",
    "Jawline · Temple · Under eye",
    "Neck (tech neck) · Hand filler · Earlobe filler",
    "BioFiller — made from your own plasma",
    "Filler dissolving"
   ]
  },
  {
   "name": "Injectables",
   "image": "assets/svc-injectables.webp",
   "href": "https://www.conciergeaesthetics.com/treatments/injectables/",
   "items": [
    "Botox Cosmetic · Dysport",
    "Lip flip",
    "Sculptra · Radiesse hyperdilute",
    "Kybella — double chin",
    "Asclera vein treatment"
   ]
  },
  {
   "name": "Laser + energy",
   "image": "assets/svc-laser.webp",
   "href": "https://www.conciergeaesthetics.com/treatments/laser-and-energy-treatments/",
   "items": [
    "CoolPeel CO2 · DEKA Pulse CO2",
    "Morpheus8 — face and body",
    "Laser Genesis · IPL photofacial",
    "Laser hair removal",
    "Laser vein treatment · Laser nail fungus",
    "ThermiVa"
   ]
  },
  {
   "name": "Skin health",
   "image": "assets/svc-skin.webp",
   "href": "https://www.conciergeaesthetics.com/treatments/skin-health/",
   "items": [
    "HydraFacial — Signature, Deluxe, Platinum",
    "SkinPen microneedling",
    "Chemical peels · Perfect Derma Peel",
    "Custom facials · dermaplaning",
    "AnteAGE exosomes",
    "Brows, lashes and sugaring"
   ]
  },
  {
   "name": "Wellness",
   "image": "assets/svc-wellness.webp",
   "href": "https://www.conciergeaesthetics.com/treatments/wellness/",
   "items": [
    "Medical weight loss — tirzepatide",
    "Vitamin infusion IV",
    "Wellness boosters — NAD, glutathione, B12, magnesium",
    "Nutrafol for hair"
   ]
  }
 ],
 "products": {
  "eyebrow": "Professional care at home",
  "heading": "Eight medical-grade brands, dispensed in clinic.",
  "lede": "AlumierMD, AnteAGE MD, Colorescience, SkinMedica, Skinbetter Science, Nutrafol, Latisse and Upneeq — ninety-six products, matched to your plan rather than picked off a shelf.",
  "href": "https://www.conciergeaesthetics.com/skincare/",
  "items": [
   {
    "name": "SkinMedica Dermal Repair Cream",
    "note": "$135",
    "image": "assets/prod-1.webp"
   },
   {
    "name": "SkinMedica E|C Dark Spot Cream",
    "note": "$90",
    "image": "assets/prod-2.webp"
   },
   {
    "name": "AlumierMD Enzymatic Peel",
    "note": "$95",
    "image": "assets/prod-3.webp"
   },
   {
    "name": "AlumierMD MicroDerm Polish",
    "note": "$76",
    "image": "assets/prod-4.webp"
   },
   {
    "name": "AlumierMD Acne Clarifying Cleanser",
    "note": "$55",
    "image": "assets/prod-5.webp"
   },
   {
    "name": "Colorescience Sunforgettable Brush",
    "note": "$70",
    "image": "assets/prod-6.webp"
   },
   {
    "name": "AnteAGE MD Biogel",
    "note": "$50",
    "image": "assets/prod-7.webp"
   },
   {
    "name": "AlumierMD Retinol Eye Gel",
    "note": "In clinic",
    "image": "assets/prod-8.webp"
   }
  ]
 },
 "membership": {
  "eyebrow": "Membership",
  "anchor": "The Concierge Club — $250 a month, fifty places.",
  "anchorSub": "Founding-member pricing, locked for the life of the membership. Their own programme, their own numbers.",
  "cta": "See the Concierge Club",
  "href": "https://www.conciergeaesthetics.com/concierge-club/",
  "images": [
   "assets/gram-2.webp",
   "assets/lobby.webp"
  ],
  "faq": [
   {
    "q": "$200 monthly Beauty Bank",
    "a": "Two hundred dollars of treatment credit every month — $2,400 a year — against whatever you actually come in for."
   },
   {
    "q": "$1 off every unit of Botox and Dysport",
    "a": "Every visit, on their own wording, without waiting for a sale."
   },
   {
    "q": "10% off select treatments, 15% off all skincare",
    "a": "CoolPeel, Morpheus8, IPL, HydraFacial, microneedling and PRP hair are the named treatments. The skincare discount covers every brand they stock."
   },
   {
    "q": "$200 birthday credit and a $100 gift card",
    "a": "A birthday credit each year, plus a hundred-dollar card to give to someone who has never been in."
   },
   {
    "q": "The terms, in their own words",
    "a": "A $99 enrolment fee and a twelve-month initial agreement, then month to month. Thirty days’ notice to cancel, and one thirty-day pause a year for medical reasons or travel. Fifty memberships, no waitlist."
   }
  ]
 },
 "proof": {
  "rating": "5.0",
  "reviewCount": "533",
  "reviewSource": "Google and Yelp, as published by the practice",
  "award": "Allergan Top 500 Practice — top 1% nationwide",
  "awardNote": "Their own homepage badge",
  "reviewers": [
   "Karane Z.",
   "Suzanne K.",
   "Kate S.",
   "Alyssa G.",
   "Julie F.",
   "Vanessa B."
  ],
  "stats": [
   {
    "n": "5.0",
    "label": "Stars across Google and Yelp"
   },
   {
    "n": "533",
    "label": "Reviews, their own published count"
   },
   {
    "n": "2009",
    "label": "Serving Orange County since"
   },
   {
    "n": "10,000+",
    "label": "Treatments performed"
   }
  ]
 },
 "faq": [
  {
   "q": "I have never had anything done. Where do I start?",
   "a": "With a consultation — thirty minutes, one-to-one with a provider. They ask what is actually bothering you, look at your face as a whole rather than the one line you noticed, take photographs for your record and walk you through a plan with exact costs before anything happens. There is no pressure to decide in the room."
  },
  {
   "q": "How much is a consultation?",
   "a": "It is a paid appointment rather than a sales visit, and the fee is credited towards your treatment if you go ahead on the day. If you decide not to, it is refunded as long as you give at least twenty-four hours’ notice. The figure is on this page."
  },
  {
   "q": "Who will be treating me? Is it a doctor?",
   "a": "Injections are performed by physician assistants who are overseen by a medical director. That medical director is Dr. Steven G. Yoelin, a board-certified ophthalmologist who runs clinical trials on facial injectables and teaches injection technique. You can see every provider by name on this page."
  },
  {
   "q": "How do I choose which provider to book with?",
   "a": "Their own answer: you will be in great hands with any of them, and they are happy to recommend one. If you tell me what you are coming in for I can point you at the right diary."
  },
  {
   "q": "Can I have the consultation and the treatment on the same day?",
   "a": "In most cases yes, for Botox and filler. Whether that is the right call is the provider’s judgement on the day rather than something to promise in advance."
  },
  {
   "q": "Will I look like I have had something done?",
   "a": "That is the most common worry, and it is the whole basis of how this practice works — artistry, precision and restraint, guided by what enhances your features rather than what changes them. Sometimes the recommendation is fewer treatments, or none."
  },
  {
   "q": "How long does a treatment take?",
   "a": "It varies with what is being done, but for injectables most people are in and out inside half an hour. Numbing time is included in your appointment, so there is no need to arrive early for it."
  },
  {
   "q": "Is there any downtime after injectables?",
   "a": "Minor swelling or bruising can happen. Most people expect to get back to their day straight away. Resurfacing lasers are a different conversation — ask about the specific treatment and your provider will be straight with you about recovery."
  },
  {
   "q": "How soon do results show, and how long do they last?",
   "a": "For the wrinkle relaxers you can start to see something in three or four days, with the full effect over one to two weeks. Filler shows almost immediately and then settles over a few weeks. Maintenance is usually talked about as three or four times a year for relaxers, and one or two for filler, depending on the product and on you."
  },
  {
   "q": "How many sessions of laser hair removal will I need?",
   "a": "Generally eight to ten visits for the best result, and the exact number depends on the area, the hair and the growth cycle. Patients tend to describe the sensation as a rubber band against the skin rather than as painful."
  },
  {
   "q": "What about microneedling — when do I see something?",
   "a": "Changes can start within days or weeks, and keep developing for around six months while collagen production stays active. A topical anaesthetic is applied first, and most people go back to their normal day immediately, with the skin a little pink for one to three days."
  },
  {
   "q": "What are Allē points and can I use them here?",
   "a": "Allē is Allergan’s own rewards programme. Points can be used across Allergan’s range — Botox, Juvéderm filler and SkinMedica skincare. Concierge are enrolled, which is what makes your treatments count, and Allē is the one discount that combines with the others."
  },
  {
   "q": "How does the Concierge Club work?",
   "a": "It is a monthly membership with a treatment credit that builds every month, a per-unit saving on the wrinkle relaxers, a discount on select treatments and on all skincare, and a birthday credit. There are fifty places and founding pricing is locked in. The figures are set out on the membership section of this page — I do not quote them out loud."
  },
  {
   "q": "Can I pay it off over time?",
   "a": "Yes. Concierge work with Cherry and with CareCredit, and applying with Cherry does not affect your credit score. They also take Apple Pay, gift cards and the usual credit cards."
  },
  {
   "q": "What is your cancellation policy?",
   "a": "Twenty-four hours’ notice for appointments under two hours, forty-eight for anything longer. If you arrive more than ten minutes late you may be asked to reschedule. Late cancellations carry a service fee."
  },
  {
   "q": "Can I bring my child or my dog?",
   "a": "Children are welcome in the building but should have another adult with them rather than come into the treatment room, so you get the provider’s full attention. Pets are asked to stay at home; service animals are always welcome."
  },
  {
   "q": "When are you open?",
   "a": "Monday, Tuesday, Thursday and Friday nine to five, and Wednesday nine to six. Closed at the weekend."
  },
  {
   "q": "Where are you?",
   "a": "113 Waterworks Way, Suite 340, Irvine — the Irvine Medical Arts Building, on Waterworks between Laguna Canyon Road and Endeavor Road, near the Irvine Spectrum. Coming off either freeway you exit at Sand Canyon and make a U-turn at Laguna Canyon; it is the newer tan medical building on the right."
  }
 ],
 "results": {
  "eyebrow": "Results",
  "heading": "Before and after, from their own gallery.",
  "lede": "Concierge publish 129 of these. They are among the best result photographs of any practice we have looked at — and they sit behind a gallery link on a homepage that takes twelve seconds to paint.",
  "categories": [
   "Lips",
   "Filler",
   "Laser + energy",
   "Tox"
  ],
  "pairs": {
   "Lips": [
    {
     "before": "assets/ba-lips-5yr-before.webp",
     "after": "assets/ba-lips-5yr-after.webp"
    },
    {
     "before": "assets/ba-lips-first-before.webp",
     "after": "assets/ba-lips-first-after.webp"
    },
    {
     "before": "assets/ba-lips-kysse-before.webp",
     "after": "assets/ba-lips-kysse-after.webp"
    }
   ],
   "Filler": [
    {
     "before": "assets/ba-undereye-before.webp",
     "after": "assets/ba-undereye-after.webp"
    },
    {
     "before": "assets/ba-fullface-before.webp",
     "after": "assets/ba-fullface-after.webp"
    },
    {
     "before": "assets/ba-hands-before.webp",
     "after": "assets/ba-hands-after.webp"
    },
    {
     "before": "assets/ba-earlobe-before.webp",
     "after": "assets/ba-earlobe-after.webp"
    },
    {
     "before": "assets/ba-sculptra-before.webp",
     "after": "assets/ba-sculptra-after.webp"
    }
   ],
   "Laser + energy": [
    {
     "before": "assets/ba-coolpeel-before.webp",
     "after": "assets/ba-coolpeel-after.webp"
    },
    {
     "before": "assets/ba-morpheus8-before.webp",
     "after": "assets/ba-morpheus8-after.webp"
    },
    {
     "before": "assets/ba-ipl-before.webp",
     "after": "assets/ba-ipl-after.webp"
    },
    {
     "before": "assets/ba-nailfungus-before.webp",
     "after": "assets/ba-nailfungus-after.webp"
    }
   ],
   "Tox": [
    {
     "before": "assets/ba-male-botox-before.webp",
     "after": "assets/ba-male-botox-after.webp"
    },
    {
     "before": "assets/ba-nefertiti-before.webp",
     "after": "assets/ba-nefertiti-after.webp"
    }
   ]
  },
  "emptyNote": ""
 },
 "extraFacts": [
  "Concierge Aesthetics have been in Orange County since 2009 and moved into their own facility on Waterworks Way in 2017. The clinic is at 113 Waterworks Way, Suite 340, Irvine, in the Irvine Medical Arts Building near the Irvine Spectrum.",
  "The practice was founded by Stacy Vencill, PA-C, MPH, who owns it and still injects.",
  "The medical director is Dr. Steven G. Yoelin, a board-certified ophthalmologist in Newport Beach who runs clinical trials on facial injectables.",
  "Injections are performed by physician assistants overseen by the medical director.",
  "Open Monday, Tuesday, Thursday and Friday nine to five, and Wednesday nine to six. Closed Saturday and Sunday.",
  "Concierge are an Allergan Top 500 practice — the top one per cent nationwide — and have been featured on KCAL News for Botox in Orange County.",
  "Payment: Apple Pay, gift cards, Visa, Mastercard, AMEX and Discover, plus Cherry and CareCredit financing for qualified applicants.",
  "Cancellations need twenty-four hours for appointments under two hours and forty-eight hours for longer ones. Arriving more than ten minutes late may mean rescheduling.",
  "Numbing time is included in the appointment, so there is no need to arrive early for it.",
  "Medical-grade skincare stocked in clinic: AlumierMD, AnteAGE MD, Colorescience, SkinMedica, Skinbetter Science, Nutrafol, Latisse and Upneeq.",
  "Children are welcome in the building with another adult to supervise them, but not in the treatment room. Pets stay at home; service animals are always welcome."
 ]
};
