/* GENERATED by build.mjs from demo-data.js — do not edit by hand. */
window.DEMO = {
 "practice": {
  "name": "Bella Med Spa & Aesthetics",
  "shortName": "Bella",
  "domain": "bellamedspadfw.com",
  "logoDark": "assets/logo-dark.webp",
  "logoLight": "assets/logo-light.webp",
  "phone": "972-435-9814",
  "phoneHref": "+19724359814",
  "instagram": "https://www.instagram.com/bella.medspa/",
  "instagramHandle": "@bella.medspa",
  "tagline": "Advanced aesthetics. Personalized care. Lasting confidence.",
  "story": "Started in a single treatment room in Highland Park; now two locations across DFW."
 },
 "sandy": {
  "name": "Sandy",
  "role": "AI receptionist",
  "voice": "Aoede",
  "greetingCard": "Hi, this is Sandy at Bella Med Spa. I can explain any treatment, tell you what suits Dallas or McKinney, and take a booking for you. What are you thinking about?",
  "panelLede": "Ask me anything about Bella’s treatments, either location, or book a time. I answer out loud.",
  "eyebrow": "Your virtual assistant",
  "heading": "Meet Sandy, the front desk that never goes home.",
  "lede": "She knows every treatment Bella offers, both addresses, and how the booking works. Ask her out loud — she answers in about a second.",
  "asks": [
   "“What’s the difference between Bella Tox and Mini Tox?”",
   "“Do you treat excessive underarm sweating?”",
   "“Can I do the 12-week Semaglutide program in McKinney?”",
   "“How much downtime after a Deep CO2?”",
   "“Book me a virtual skin analysis on Thursday.”"
  ],
  "extraFacts": [
   "Evolus partner clinic. ZO® Skin Health dispensed in clinic.",
   "Injectables are delivered by the practice’s own Beauty Nurses."
  ]
 },
 "locations": [
  {
   "id": "dallas",
   "name": "Dallas",
   "address": "412 S Llewellyn Ave, #150, Dallas, TX 75208",
   "hint": "Bishop Arts / Oak Cliff",
   "parking": "Street parking on S Llewellyn and the surrounding Bishop Arts blocks.",
   "lat": 32.7417813,
   "lon": -96.8319395,
   "hours": {
    "1": [
     9,
     18
    ],
    "2": [
     9,
     18
    ],
    "3": [
     9,
     18
    ],
    "4": [
     9,
     19
    ],
    "5": [
     9,
     17
    ],
    "6": [
     10,
     15
    ]
   }
  },
  {
   "id": "mckinney",
   "name": "McKinney",
   "address": "3701 Eldorado Parkway, Suite D, McKinney, TX 75070",
   "hint": "North of Dallas, off Eldorado",
   "parking": "On-site parking at the Eldorado Parkway suites.",
   "lat": 33.167965,
   "lon": -96.668015,
   "hours": {
    "1": [
     10,
     18
    ],
    "2": [
     9,
     18
    ],
    "3": [
     9,
     18
    ],
    "4": [
     9,
     18
    ],
    "5": [
     9,
     16
    ],
    "6": [
     10,
     14
    ]
   }
  }
 ],
 "bookable": [
  {
   "id": "consult",
   "group": "Start here",
   "name": "Consultation",
   "mins": 30,
   "note": "In person or virtual"
  },
  {
   "id": "analysis",
   "group": "Start here",
   "name": "Skin analysis",
   "mins": 30,
   "note": "In person or virtual"
  },
  {
   "id": "bella-tox",
   "group": "Injectables",
   "name": "Bella Tox",
   "mins": 45
  },
  {
   "id": "mini-tox",
   "group": "Injectables",
   "name": "Mini Tox",
   "mins": 30
  },
  {
   "id": "mature-tox",
   "group": "Injectables",
   "name": "Mature Tox",
   "mins": 45
  },
  {
   "id": "filler",
   "group": "Injectables",
   "name": "Filler",
   "mins": 60
  },
  {
   "id": "lip-flip",
   "group": "Injectables",
   "name": "Lip flip",
   "mins": 30
  },
  {
   "id": "axilla",
   "group": "Injectables",
   "name": "Axilla — underarm sweating",
   "mins": 45
  },
  {
   "id": "virtuerf",
   "group": "Skin",
   "name": "VirtueRF microneedling",
   "mins": 75
  },
  {
   "id": "facial",
   "group": "Skin",
   "name": "Facial",
   "mins": 60
  },
  {
   "id": "peel",
   "group": "Skin",
   "name": "Peel",
   "mins": 45
  },
  {
   "id": "pdo",
   "group": "Skin",
   "name": "PDO threads",
   "mins": 90
  },
  {
   "id": "glp1",
   "group": "Wellness",
   "name": "Semaglutide GLP-1 consultation",
   "mins": 30
  },
  {
   "id": "b12",
   "group": "Wellness",
   "name": "B12 lipotropic shot",
   "mins": 15
  },
  {
   "id": "coolpeel",
   "group": "Laser",
   "name": "CO2 Cool Peel",
   "mins": 60
  },
  {
   "id": "deep-co2",
   "group": "Laser",
   "name": "Deep CO2 resurfacing",
   "mins": 90
  },
  {
   "id": "lhr",
   "group": "Laser",
   "name": "Laser hair removal",
   "mins": 30
  }
 ],
 "treatments": [
  {
   "name": "Injectables",
   "image": "assets/svc-injectables.webp",
   "href": "https://bellamedspadfw.com/our-services/injectables/",
   "items": [
    "Bella Tox · Mini Tox · Mature Tox",
    "Filler · Non-surgical nose job",
    "Lip flip · Brow lift",
    "Jawline slimming",
    "Axilla — underarm sweating"
   ]
  },
  {
   "name": "Skin",
   "image": "assets/svc-skin.webp",
   "href": "https://bellamedspadfw.com/our-services/skin-treatments/",
   "items": [
    "VirtueRF microneedling",
    "Facials · Peels",
    "PDO threads",
    "Brows & lashes · Waxing",
    "Skin analysis — in person or virtual"
   ]
  },
  {
   "name": "Wellness",
   "image": "assets/svc-wellness.webp",
   "href": "https://bellamedspadfw.com/our-services/wellness/",
   "items": [
    "Semaglutide GLP-1 shot",
    "6, 9 and 12-week programs",
    "B12 lipotropic",
    "Peptides",
    "Hair transplant"
   ]
  },
  {
   "name": "Laser",
   "image": "assets/svc-laser.webp",
   "href": "https://bellamedspadfw.com/our-services/laser/",
   "items": [
    "CO2 Cool Peel",
    "Deep CO2 resurfacing",
    "PlaDuo plasma",
    "Laser hair removal"
   ]
  }
 ],
 "products": {
  "eyebrow": "Professional care at home",
  "heading": "ZO® Skin Health, dispensed in clinic.",
  "lede": "Bella's best sellers. Physician-grade, matched to your plan rather than picked off a shelf.",
  "href": "https://bellamedspadfw.com/products/",
  "items": [
   {
    "name": "Gentle Cleanser",
    "note": "Best seller",
    "image": "assets/prod-gentle-cleanser.webp"
   },
   {
    "name": "Exfoliating Polish",
    "note": "Best seller",
    "image": "assets/prod-exfoliating-polish.webp"
   },
   {
    "name": "Complexion Renewal Pads",
    "note": "Best seller",
    "image": "assets/prod-complexion-renewal-pads.webp"
   },
   {
    "name": "Oil Control Pads",
    "note": "Best seller",
    "image": "assets/prod-oil-control-pads.webp"
   },
   {
    "name": "Daily Power Defense",
    "note": "Best seller",
    "image": "assets/prod-daily-power-defense.webp"
   },
   {
    "name": "Firming Serum",
    "note": "Best seller",
    "image": "assets/prod-firming-serum.webp"
   },
   {
    "name": "Wrinkle + Texture",
    "note": "Best seller",
    "image": "assets/prod-wrinkle-texture.webp"
   }
  ]
 },
 "membership": {
  "eyebrow": "Exclusive membership",
  "anchor": "Member pricing on every visit, all year.",
  "anchorSub": "Plus priority booking at both locations and a plan that is reviewed as you go, rather than restarted every time.",
  "cta": "Explore membership",
  "href": "https://bellamedspadfw.com/membership-program/",
  "images": [
   "assets/member-2.webp",
   "assets/member-3.webp"
  ],
  "faq": [
   {
    "q": "What's included",
    "a": "Member-only pricing on treatments, exclusive seasonal savings, and priority booking in Dallas and McKinney."
   },
   {
    "q": "Your plan",
    "a": "A personalized treatment plan across the year, adjusted as your skin and goals change."
   },
   {
    "q": "Laser membership",
    "a": "A separate laser membership runs alongside, for hair removal and resurfacing courses."
   },
   {
    "q": "The number",
    "a": "Bella does not publish a monthly price. A visible “from” figure is the single fastest way to turn browsers into members."
   }
  ]
 },
 "proof": {
  "rating": "4.8",
  "reviewCount": "523+",
  "reviewSource": "Google",
  "award": "Best of Advocate 2025",
  "awardNote": "Voted by Dallas readers",
  "reviewers": [
   "Nicole Nichols",
   "Felipa Gonzalez",
   "Jarline Deleon",
   "Ivonne Diaz",
   "Jorge Vi"
  ],
  "stats": [
   {
    "n": "4.8",
    "label": "Average Google rating"
   },
   {
    "n": "523+",
    "label": "Reviews from real guests"
   },
   {
    "n": "2025",
    "label": "Best of Advocate, Dallas"
   },
   {
    "n": "2",
    "label": "Locations across DFW"
   }
  ]
 },
 "faq": [],
 "results": {
  "eyebrow": "Results",
  "heading": "Before and after, by treatment.",
  "lede": "One pair at a time, chosen by category, so nobody has to scroll a wall of thumbnails to find the thing they came for.",
  "categories": [
   "Injectables",
   "Skin",
   "Laser",
   "Wellness"
  ],
  "pairs": {},
  "emptyNote": "<strong>These frames are empty on purpose.</strong> Bella has before-and-after results on Instagram, but none of them are on the website — which is where someone deciding on a treatment actually looks. Drop the photographs in and this section fills itself."
 },
 "extraFacts": [
  "Evolus partner clinic. ZO® Skin Health dispensed in clinic.",
  "Injectables are delivered by the practice’s own Beauty Nurses."
 ]
};
