/* GENERATED by build.mjs from demo-data.js — do not edit by hand. */
window.DEMO = {
 "practice": {
  "name": "Fountain of Youth Medical Spa",
  "shortName": "Fountain of Youth",
  "domain": "fountainmedicalspa.com",
  "logoDark": "assets/logo-dark.webp",
  "logoLight": "assets/logo-light.webp",
  "phone": "361-576-9100",
  "phoneHref": "+13615769100",
  "instagram": "https://www.instagram.com/fountainofyouthmedicalspa",
  "instagramHandle": "@fountainofyouthmedicalspa",
  "tagline": "Look and feel your best, at any age.",
  "story": "Victoria’s first medical spa, opened in 2007 and led by Dr. Nhi Le, MD — a board-certified internist who also runs Texas Medical & Wellness Clinic next door."
 },
 "sandy": {
  "name": "Sandy",
  "role": "AI receptionist",
  "voice": "Aoede",
  "model": "gemini-3.1-flash-live-preview",
  "tuning": {
   "endSensitivity": "END_SENSITIVITY_LOW",
   "silenceMs": 1400,
   "thinkingLevel": "LOW",
   "proactiveAudio": false,
   "affectiveDialog": false
  },
  "talkingPoints": {
   "BOTOX®": "The wrinkle relaxer most people have heard of. It softens the lines that come from movement — forehead, frown lines, crow’s feet. A good first treatment for somebody who has never had anything done.",
   "DAXXIFY®": "A newer wrinkle relaxer, sometimes chosen by people who want to stretch the interval between appointments. Whether it suits you is a consultation question.",
   "XEOMIN®": "A stripped-back formulation with no additional proteins, often discussed with people who have had injectables for years.",
   "JUVÉDERM® filler": "A hyaluronic acid filler for lips, cheeks, smile lines and jawline. It adds volume and contour rather than relaxing movement, which is the fundamental difference between filler and tox.",
   "Restylane®": "Another hyaluronic acid family, with different products suited to different depths and areas. Which family gets used is decided at consultation.",
   "Sculptra®": "Works gradually by encouraging your own collagen rather than filling immediately, so it suits somebody thinking in terms of a year rather than a week.",
   "Lip enhancement": "Filler placed in the lip itself for shape and volume. The conversation is mostly about how much change you actually want, which is usually less than people expect.",
   "Kybella®": "An injectable used under the chin. A series rather than a single visit, and suitability is assessed first.",
   "YLift®": "A non-surgical lift. Filler is placed deep along the bone structure to restore the scaffolding of the face, rather than filling lines at the surface. It is one of the things this practice is known for, and there is a gallery of results on their site.",
   "VolumaLift™": "A lifting approach built on volume restoration, discussed alongside YLift when working out which suits your face.",
   "MINT™ thread lift": "Dissolvable threads placed under the skin to reposition tissue and encourage collagen along the thread line. A middle option between injectables and surgery.",
   "PRP facelift": "Uses a component of your own blood, prepared in clinic, to support the skin’s own repair processes. Often combined with microneedling.",
   "Sofwave™ skin tightening": "An energy-based treatment for laxity that does not break the surface of the skin, so people generally carry on with their day afterwards.",
   "RF microneedling": "Fine needles create controlled micro-channels while delivering heat below the surface, prompting the skin to rebuild collagen over the following weeks. Usually a short course.",
   "HydraFacial™": "Cleansing, exfoliation, extraction and hydration in one treatment. Good for regular maintenance between clinical treatments.",
   "Celebrity Peel": "One of the signature facials here, chosen when somebody wants visible freshening before an event.",
   "Champagne Facial": "The indulgent end of the facial menu, and one of the treatments included in the Elite VIP membership each month.",
   "AQUAGOLD® Fine Touch": "A micro-channel device that delivers a tailored blend into the very top layer of skin. Chosen for overall glow rather than for a specific line.",
   "CO2 fractional resurfacing": "The more intensive resurfacing option, for texture and established sun damage. It needs real planning around your calendar, so aftercare and timing get covered carefully at consultation.",
   "Fraxel Dual resurfacing": "Fractional resurfacing aimed at tone, texture and pigment, usually as a short course.",
   "IPL photofacial": "Light-based treatment for redness, pigment and unevenness. Normally a course, and often paired with a skincare plan.",
   "Laser hair removal": "A course of treatments targeting hair while it is in its active growth phase, which is why it is spaced over several sessions.",
   "EMSCULPT NEO®": "A body treatment that works on muscle and fat at the same time, without surgery. Suitability is discussed first.",
   "EMSELLA® chair": "A chair you sit on, fully clothed, used for pelvic floor strength. People are often surprised this exists — it comes up a lot in the intimate wellness side of the practice.",
   "Hormone and thyroid testing": "Bloodwork rather than guesswork. Thyroid, sex hormones and adrenal function are all tested here, and Dr. Le reads them herself because she is an internist. It is usually where the conversation starts if you are tired, gaining weight, or not feeling like yourself.",
   "Functional and screening tests": "A fuller panel than most people expect from a medical spa — micronutrients, food sensitivity, gut health, cardiovascular and metabolic markers, genetic testing, urine heavy metals, and the Galleri multi-cancer screening test. These are optional, they are ordered by a physician, and which ones are worth doing is a consultation question rather than a menu you pick from.",
   "Bio-identical hormone consultation": "Dr. Le is an internist, so hormones are properly investigated here rather than guessed at. It starts with a conversation and testing, not a prescription.",
   "Medical weight loss consultation": "A medically supervised programme that begins with a consultation about your history and whether it is appropriate for you, with monitoring throughout.",
   "Peptide therapy consultation": "Peptides are short chains of amino acids that act as messengers, supporting processes your body already runs. Run here as a medically guided programme.",
   "IV therapy": "Hydration and nutrients by drip — there is a menu of them, from a Myers’ Cocktail to NAD+. Usually part of a wider plan.",
   "PRP": "Uses a component of your own blood to support repair. Used on the face, and also for hair and for joints on the regenerative side of the practice.",
   "Membership": "Three of them, each banking a monthly amount toward treatment and carrying a standing discount on services and skincare. I do not quote figures out loud — they are set out on the membership section of this page, and the front desk will walk you through them.",
   "Consultation": "Where everything starts. Somebody looks at your skin and listens to what is bothering you, explains the options, and you decide from there."
  },
  "soundsLike": [
   "\"YLift\" may be heard as why lift, y lift, wi-fi lift or uplift.",
   "\"Sofwave\" may be heard as soft wave, sof wave or soap wave.",
   "\"AQUAGOLD\" may be heard as aqua gold or acquired gold.",
   "\"DAXXIFY\" may be heard as daxify, dax defy or taxify.",
   "\"Jeuveau\" may be heard as juvo, jouveau or youво.",
   "\"Xeomin\" may be heard as zeomin, xeo min or see o min.",
   "\"Fraxel\" may be heard as fractal, frackle or fraxil.",
   "\"PicoSure\" may be heard as pico sure or peek o sure.",
   "\"EMSELLA\" may be heard as em sella, mm sella or umbrella.",
   "\"EMSCULPT\" may be heard as em sculpt or m sculpt.",
   "\"Sculptra\" may be heard as sculptura or sculpt draw.",
   "\"Dr. Nhi Le\" is pronounced \"Dr. Lei\", and may be heard as doctor Lee, doctor Nee or doctor Lay.",
   "\"Fountain of Youth\" may be heard as fountain of you or mountain of youth."
  ],
  "greetingCard": "Hi, this is Sandy at Fountain of Youth Medical Spa in Victoria. I can explain any treatment, tell you about Dr. Le, and take a booking for you. What are you thinking about?",
  "panelLede": "Ask me anything about the treatments, the memberships or Dr. Le, and I can book you a time. I answer out loud.",
  "eyebrow": "Your virtual assistant",
  "heading": "Meet Sandy, the front desk that never goes home.",
  "lede": "She knows all eighty treatments, who is on the team, the opening hours and how the booking works. Ask her out loud — she answers in about a second.",
  "asks": [
   "“What is a YLift?”",
   "“Is there actually a doctor there?”",
   "“What is the difference between tox and filler?”",
   "“Do you do hormone testing?”",
   "“Book me a consultation on Thursday.”"
  ],
  "extraFacts": [
   "Fountain of Youth opened in 2007 and was the first medical spa in Victoria, Texas.",
   "Dr. Nhi Le, MD is the medical director — a board-certified internist with advanced certification in Functional and Regenerative Medicine, and a fellowship in anti-aging medicine completed in 2013.",
   "The clinic is at 4701 North Navarro Street, Victoria, Texas 77904. Open Monday to Thursday nine to six and Friday nine to five. Closed at the weekend.",
   "Adriana Arriaga is the RN injector, Shelby Reeves the medical aesthetician, Melissa Garcia the patient coordinator and Jessica Sierra the operations manager.",
   "Testing available here includes thyroid, sex hormones, adrenal function, micronutrients, food sensitivity, gut health, cardiovascular and metabolic markers, genetic testing, urine heavy metals, and the Galleri multi-cancer screening test.",
   "The Skin Bar carries iS Clinical and RevitaLash."
  ]
 },
 "locations": [
  {
   "id": "victoria",
   "name": "Victoria",
   "address": "4701 N Navarro Street, Victoria, TX 77904",
   "hint": "North Navarro, Victoria",
   "parking": "Parking on site.",
   "lat": 28.8543,
   "lon": -97.0086,
   "hours": {
    "1": [
     9,
     18
    ],
    "2": [
     9,
     18
    ],
    "3": [
     9,
     18
    ],
    "4": [
     9,
     18
    ],
    "5": [
     9,
     17
    ]
   }
  }
 ],
 "bookable": [
  {
   "id": "consult",
   "group": "Start here",
   "name": "Consultation",
   "mins": 30
  },
  {
   "id": "wellness-consult",
   "group": "Start here",
   "name": "Wellness consultation with Dr. Le",
   "mins": 45
  },
  {
   "id": "botox",
   "group": "Injectables",
   "name": "BOTOX®",
   "mins": 30
  },
  {
   "id": "daxxify",
   "group": "Injectables",
   "name": "DAXXIFY®",
   "mins": 30
  },
  {
   "id": "xeomin",
   "group": "Injectables",
   "name": "XEOMIN®",
   "mins": 30
  },
  {
   "id": "juvederm",
   "group": "Injectables",
   "name": "JUVÉDERM® filler",
   "mins": 60
  },
  {
   "id": "restylane",
   "group": "Injectables",
   "name": "Restylane®",
   "mins": 60
  },
  {
   "id": "sculptra",
   "group": "Injectables",
   "name": "Sculptra®",
   "mins": 60
  },
  {
   "id": "lips",
   "group": "Injectables",
   "name": "Lip enhancement",
   "mins": 45
  },
  {
   "id": "kybella",
   "group": "Injectables",
   "name": "Kybella®",
   "mins": 45
  },
  {
   "id": "ylift",
   "group": "Lifting",
   "name": "YLift®",
   "mins": 90
  },
  {
   "id": "volumalift",
   "group": "Lifting",
   "name": "VolumaLift™",
   "mins": 90
  },
  {
   "id": "mint",
   "group": "Lifting",
   "name": "MINT™ thread lift",
   "mins": 90
  },
  {
   "id": "prp-facelift",
   "group": "Lifting",
   "name": "PRP facelift",
   "mins": 75
  },
  {
   "id": "sofwave",
   "group": "Lifting",
   "name": "Sofwave™ skin tightening",
   "mins": 60
  },
  {
   "id": "rf-microneedling",
   "group": "Skin",
   "name": "RF microneedling",
   "mins": 75
  },
  {
   "id": "microneedling",
   "group": "Skin",
   "name": "SkinStylus™ microneedling",
   "mins": 60
  },
  {
   "id": "hydrafacial",
   "group": "Skin",
   "name": "HydraFacial™",
   "mins": 60
  },
  {
   "id": "diamondglow",
   "group": "Skin",
   "name": "DiamondGlow™ facial",
   "mins": 60
  },
  {
   "id": "celebrity-peel",
   "group": "Skin",
   "name": "Celebrity Peel",
   "mins": 60
  },
  {
   "id": "champagne",
   "group": "Skin",
   "name": "Champagne Facial",
   "mins": 60
  },
  {
   "id": "aquagold",
   "group": "Skin",
   "name": "AQUAGOLD® Fine Touch",
   "mins": 45
  },
  {
   "id": "co2",
   "group": "Lasers",
   "name": "CO2 fractional resurfacing",
   "mins": 90
  },
  {
   "id": "fraxel",
   "group": "Lasers",
   "name": "Fraxel Dual resurfacing",
   "mins": 75
  },
  {
   "id": "picosure",
   "group": "Lasers",
   "name": "PicoSure® Focus™",
   "mins": 45
  },
  {
   "id": "ipl",
   "group": "Lasers",
   "name": "IPL photofacial",
   "mins": 45
  },
  {
   "id": "lhr",
   "group": "Lasers",
   "name": "Laser hair removal",
   "mins": 30
  },
  {
   "id": "tattoo",
   "group": "Lasers",
   "name": "Laser tattoo removal",
   "mins": 30
  },
  {
   "id": "emsculpt",
   "group": "Body",
   "name": "EMSCULPT NEO®",
   "mins": 45
  },
  {
   "id": "emsella",
   "group": "Body",
   "name": "EMSELLA® chair",
   "mins": 30
  },
  {
   "id": "hormones",
   "group": "Wellness",
   "name": "Bio-identical hormone consultation",
   "mins": 45
  },
  {
   "id": "testing",
   "group": "Wellness",
   "name": "Hormone and thyroid testing",
   "mins": 30
  },
  {
   "id": "weight",
   "group": "Wellness",
   "name": "Medical weight loss consultation",
   "mins": 45
  },
  {
   "id": "peptides",
   "group": "Wellness",
   "name": "Peptide therapy consultation",
   "mins": 30
  },
  {
   "id": "iv",
   "group": "Wellness",
   "name": "IV therapy",
   "mins": 45
  },
  {
   "id": "nad",
   "group": "Wellness",
   "name": "NAD+ therapy",
   "mins": 90
  },
  {
   "id": "prp",
   "group": "Regenerative",
   "name": "PRP",
   "mins": 60
  },
  {
   "id": "exosomes",
   "group": "Regenerative",
   "name": "Exosomes",
   "mins": 60
  }
 ],
 "treatments": [
  {
   "name": "Injectables",
   "image": "assets/svc-injectables.webp",
   "href": "https://www.fountainmedicalspa.com/",
   "items": [
    "BOTOX® · Dysport® · DAXXIFY®",
    "Jeuveau® · XEOMIN® · Letybo®",
    "JUVÉDERM® · Restylane® · RHA®",
    "Radiesse® · Sculptra®",
    "Lip enhancement · Hand rejuvenation",
    "Kybella® · Sclerotherapy"
   ]
  },
  {
   "name": "Non-surgical lift",
   "image": "assets/svc-lift.webp",
   "href": "https://www.fountainmedicalspa.com/",
   "items": [
    "YLift®",
    "VolumaLift™",
    "PRP facelift",
    "Non-surgical facelift",
    "Non-surgical nose job",
    "Sofwave™ skin tightening"
   ]
  },
  {
   "name": "Threads & skin",
   "image": "assets/svc-threads.webp",
   "href": "https://www.fountainmedicalspa.com/",
   "items": [
    "MINT™ thread lift",
    "RF microneedling · SkinStylus™ · Dermapen®",
    "CO2 fractional · Fraxel Dual · PicoSure® Focus™",
    "IPL photofacial · RevLite®",
    "Celebrity Peel · Champagne Facial",
    "HydraFacial™ · DiamondGlow™ · AQUAGOLD®"
   ]
  },
  {
   "name": "Wellness & regenerative",
   "image": "assets/svc-skinbar.webp",
   "href": "https://www.fountainmedicalspa.com/",
   "items": [
    "Bio-identical hormones · thyroid testing",
    "Medical weight loss · peptide therapy",
    "PRP · exosomes · stem cell therapy",
    "IV therapy · NAD+ · Myers’ Cocktail",
    "EMSCULPT NEO® · EMSELLA® chair",
    "Galleri® multi-cancer screening"
   ]
  }
 ],
 "products": {
  "eyebrow": "",
  "heading": "",
  "lede": "",
  "href": "",
  "items": []
 },
 "membership": {
  "eyebrow": "Membership",
  "anchor": "Three memberships, from $79 a month.",
  "anchorSub": "Each one banks a monthly amount against treatment and carries a standing discount. Published on their site, and worth far more prominence than it currently gets.",
  "cta": "Explore membership",
  "href": "https://www.fountainmedicalspa.com/about-fountain-of-youth/memberships/",
  "images": [
   "assets/member-2.webp",
   "assets/member-3.webp"
  ],
  "faq": [
   {
    "q": "Tox Vault — $79 a month",
    "a": "Every dollar banks toward future treatment, with 15% off all tox and filler, and a complimentary dermaplane facial on signing up."
   },
   {
    "q": "Elite VIP Skin Rejuvenation — $269 a month",
    "a": "A fifty-minute rejuvenating session each month — Celebrity Peel, Champagne Facial, IPL or microneedling — plus 20% off all services and 15% off skincare and supplements."
   },
   {
    "q": "Ultimate Ageless VIP — $469 a month",
    "a": "A premium monthly treatment such as RF microneedling, Sofwave or Fraxel, with 25% off services and 25% off in-store skincare, and Sculptra and neck Sofwave milestones along the way."
   },
   {
    "q": "Why it matters",
    "a": "A membership turns a visitor who books once into a patient who comes back monthly. Fountain of Youth already built three of them. They currently live behind an About menu, which is the single easiest thing on this whole page to fix."
   }
  ]
 },
 "proof": {
  "rating": "",
  "reviewCount": "",
  "reviewSource": "",
  "award": "Victoria’s first medical spa",
  "awardNote": "Opened 2007",
  "reviewers": [],
  "stats": [
   {
    "n": "2007",
    "label": "Victoria’s first medical spa"
   },
   {
    "n": "16+",
    "label": "Years Dr. Le has practised internal medicine"
   },
   {
    "n": "6",
    "label": "Boards and colleges she belongs to"
   },
   {
    "n": "80+",
    "label": "Treatments offered under one roof"
   }
  ]
 },
 "faq": [
  {
   "q": "I have never had anything done. Where do I start?",
   "a": "With a consultation. Dr. Le or a member of the team looks at your skin, listens to what is actually bothering you, and explains the options and what each involves. Plenty of people book one and decide to do nothing that day — that is a perfectly normal outcome."
  },
  {
   "q": "Is there really a doctor here?",
   "a": "Yes. Dr. Nhi Le, MD is the medical director. She is a board-certified internist with advanced certification in Functional and Regenerative Medicine, and she also runs Texas Medical and Wellness Clinic. That is unusual for a medical spa and it is the reason the wellness side of the menu exists."
  },
  {
   "q": "Who will actually be treating me?",
   "a": "Injectables are given by Adriana, our RN injector, and skin treatments by Shelby, our medical aesthetician, with Dr. Le overseeing. You can ask for the same provider each visit, and most patients do."
  },
  {
   "q": "Why would a med spa run blood tests?",
   "a": "Because tiredness, weight and skin quality often trace back to something measurable — thyroid, hormones, micronutrients. Dr. Le is an internist, so she can investigate that rather than treat only what shows on the surface. It is optional, and it starts with a conversation."
  },
  {
   "q": "What is the difference between tox and filler?",
   "a": "Tox relaxes the muscles that create movement lines. Filler adds volume or structure where the face has lost it. Which one, where, and how much is a judgement about your face rather than a package you choose in advance."
  },
  {
   "q": "What is a YLift?",
   "a": "A non-surgical lift done with filler placed deep along the bone structure to restore the scaffolding of the face, rather than filling lines at the surface. It is one of the things this practice is known for, and there is a gallery of results."
  },
  {
   "q": "How long do results last?",
   "a": "It depends on the treatment and on you. Tox is generally discussed in months, filler in a year or more, and threads and lifts differently again. Your provider will give you a realistic range for your own plan rather than a number off a chart."
  },
  {
   "q": "Does it hurt?",
   "a": "Most people describe injectables as a quick pinch, and numbing is used where it helps. Lasers and resurfacing feel different again. Ask about the specific treatment you are considering and we will tell you honestly what to expect."
  },
  {
   "q": "How much downtime should I plan for?",
   "a": "It varies from none to a genuine recovery period, depending on what you have. Tell us about any event you have coming up and we will time the plan around it."
  },
  {
   "q": "How does the membership work?",
   "a": "There are three, and each one banks a monthly amount toward treatment and carries a standing discount on services and skincare. Ask me about a specific one and I will tell you what is in it — the figures are set out further down this page."
  },
  {
   "q": "Do you treat men?",
   "a": "Yes, and there is a part of the menu written for it — the Gentleman’s Facial, tox, body contouring, hair restoration and the hormone side of the practice."
  },
  {
   "q": "When are you open?",
   "a": "Monday to Thursday nine to six, Friday nine to five. Closed Saturday and Sunday."
  },
  {
   "q": "Where are you?",
   "a": "4701 North Navarro Street in Victoria, Texas. Ask me for directions and I will point you at the route planner."
  }
 ],
 "results": {
  "eyebrow": "Results",
  "heading": "Before and after, from their gallery.",
  "lede": "Forty-six frames sit on a gallery page most visitors never reach. Here they are beside the treatment that produced them.",
  "categories": [
   "Injectables",
   "Threads",
   "YLift"
  ],
  "pairs": {
   "Injectables": [
    {
     "before": "assets/ba-botox-1-before.webp",
     "after": "assets/ba-botox-1-after.webp"
    },
    {
     "before": "assets/ba-botox-2-before.webp",
     "after": "assets/ba-botox-2-after.webp"
    },
    {
     "before": "assets/ba-botox-3-before.webp",
     "after": "assets/ba-botox-3-after.webp"
    }
   ],
   "Threads": [
    {
     "before": "assets/ba-thread-1-before.webp",
     "after": "assets/ba-thread-1-after.webp"
    },
    {
     "before": "assets/ba-thread-2-before.webp",
     "after": "assets/ba-thread-2-after.webp"
    }
   ],
   "YLift": [
    {
     "before": "assets/ba-ylift-1-before.webp",
     "after": "assets/ba-ylift-1-after.webp"
    },
    {
     "before": "assets/ba-ylift-2-before.webp",
     "after": "assets/ba-ylift-2-after.webp"
    },
    {
     "before": "assets/ba-ylift-3-before.webp",
     "after": "assets/ba-ylift-3-after.webp"
    }
   ]
  },
  "emptyNote": ""
 },
 "extraFacts": [
  "Fountain of Youth opened in 2007 and was the first medical spa in Victoria, Texas.",
  "Dr. Nhi Le, MD is the medical director — a board-certified internist with advanced certification in Functional and Regenerative Medicine, and a fellowship in anti-aging medicine completed in 2013.",
  "The clinic is at 4701 North Navarro Street, Victoria, Texas 77904. Open Monday to Thursday nine to six and Friday nine to five. Closed at the weekend.",
  "Adriana Arriaga is the RN injector, Shelby Reeves the medical aesthetician, Melissa Garcia the patient coordinator and Jessica Sierra the operations manager.",
  "Testing available here includes thyroid, sex hormones, adrenal function, micronutrients, food sensitivity, gut health, cardiovascular and metabolic markers, genetic testing, urine heavy metals, and the Galleri multi-cancer screening test.",
  "The Skin Bar carries iS Clinical and RevitaLash."
 ]
};
